mappings:
- ad_url_id: '10048'
  ad_url_name: ''
- ad_url_id: '10050'
  ad_url_name: ''
- ad_url_id: '10051'
  ad_url_name: ''
- ad_url_id: '10130'
  ad_url_name: ''
- ad_url_id: '10136'
  ad_url_name: ''
- ad_url_id: '10140'
  ad_url_name: ''
- ad_url_id: '10142'
  ad_url_name: ''
- ad_url_id: '10145'
  ad_url_name: ''
- ad_url_id: '10146'
  ad_url_name: ''
- ad_url_id: '10147'
  ad_url_name: ''
- ad_url_id: '10275'
  ad_url_name: ''
- ad_url_id: '10276'
  ad_url_name: ''
- ad_url_id: '10277'
  ad_url_name: ''
- ad_url_id: '10284'
  ad_url_name: ''
- ad_url_id: '10286'
  ad_url_name: ''
- ad_url_id: '10287'
  ad_url_name: ''
- ad_url_id: '10290'
  ad_url_name: ''
- ad_url_id: '10292'
  ad_url_name: ''
- ad_url_id: '10293'
  ad_url_name: ''
- ad_url_id: '10464'
  ad_url_name: ''
- ad_url_id: '10506'
  ad_url_name: ''
- ad_url_id: '10507'
  ad_url_name: ''
- ad_url_id: '10508'
  ad_url_name: ''
- ad_url_id: '10510'
  ad_url_name: ''
- ad_url_id: '10515'
  ad_url_name: ''
- ad_url_id: '10642'
  ad_url_name: ''
- ad_url_id: '10644'
  ad_url_name: ''
- ad_url_id: '10653'
  ad_url_name: ''
- ad_url_id: '10656'
  ad_url_name: ''
- ad_url_id: '10658'
  ad_url_name: ''
- ad_url_id: '10659'
  ad_url_name: ''
- ad_url_id: '10724'
  ad_url_name: ''
- ad_url_id: '10769'
  ad_url_name: ''
- ad_url_id: '10775'
  ad_url_name: ''
- ad_url_id: '10779'
  ad_url_name: ''
- ad_url_id: '10789'
  ad_url_name: ''
- ad_url_id: '10790'
  ad_url_name: ''
- ad_url_id: '10791'
  ad_url_name: ''
- ad_url_id: '10793'
  ad_url_name: ''
- ad_url_id: '10794'
  ad_url_name: ''
- ad_url_id: '10795'
  ad_url_name: ''
- ad_url_id: '10796'
  ad_url_name: ''
- ad_url_id: '10797'
  ad_url_name: ''
- ad_url_id: '10798'
  ad_url_name: ''
- ad_url_id: '10801'
  ad_url_name: ''
- ad_url_id: '10802'
  ad_url_name: ''
- ad_url_id: '10806'
  ad_url_name: ''
- ad_url_id: '10808'
  ad_url_name: ''
- ad_url_id: '10809'
  ad_url_name: ''
- ad_url_id: '10811'
  ad_url_name: ''
- ad_url_id: '10822'
  ad_url_name: ''
- ad_url_id: '10908'
  ad_url_name: ''
- ad_url_id: '10995'
  ad_url_name: ''
- ad_url_id: '10996'
  ad_url_name: ''
- ad_url_id: '10997'
  ad_url_name: ''
- ad_url_id: '10999'
  ad_url_name: ''
- ad_url_id: '11000'
  ad_url_name: ''
- ad_url_id: '11001'
  ad_url_name: ''
- ad_url_id: '11003'
  ad_url_name: ''
- ad_url_id: '11006'
  ad_url_name: ''
- ad_url_id: '11007'
  ad_url_name: ''
- ad_url_id: '11010'
  ad_url_name: ''
- ad_url_id: '11011'
  ad_url_name: ''
- ad_url_id: '11012'
  ad_url_name: ''
- ad_url_id: '11014'
  ad_url_name: ''
- ad_url_id: '11016'
  ad_url_name: ''
- ad_url_id: '11017'
  ad_url_name: ''
- ad_url_id: '11018'
  ad_url_name: ''
- ad_url_id: '11019'
  ad_url_name: ''
- ad_url_id: '11021'
  ad_url_name: ''
- ad_url_id: '11022'
  ad_url_name: ''
- ad_url_id: '11027'
  ad_url_name: ''
- ad_url_id: '11028'
  ad_url_name: ''
- ad_url_id: '11032'
  ad_url_name: ''
- ad_url_id: '11033'
  ad_url_name: ''
- ad_url_id: '11034'
  ad_url_name: ''
- ad_url_id: '11036'
  ad_url_name: ''
- ad_url_id: '11037'
  ad_url_name: ''
- ad_url_id: '11039'
  ad_url_name: ''
- ad_url_id: '11040'
  ad_url_name: ''
- ad_url_id: '11042'
  ad_url_name: ''
- ad_url_id: '11043'
  ad_url_name: ''
- ad_url_id: '11046'
  ad_url_name: ''
- ad_url_id: '11050'
  ad_url_name: ''
- ad_url_id: '11051'
  ad_url_name: ''
- ad_url_id: '11053'
  ad_url_name: ''
- ad_url_id: '11057'
  ad_url_name: ''
- ad_url_id: '11058'
  ad_url_name: ''
- ad_url_id: '11118'
  ad_url_name: ''
- ad_url_id: '11120'
  ad_url_name: ''
- ad_url_id: '11121'
  ad_url_name: ''
- ad_url_id: '11125'
  ad_url_name: ''
- ad_url_id: '11154'
  ad_url_name: ''
- ad_url_id: '11215'
  ad_url_name: ''
- ad_url_id: '11218'
  ad_url_name: ''
- ad_url_id: '11274'
  ad_url_name: ''
- ad_url_id: '11275'
  ad_url_name: ''
- ad_url_id: '11276'
  ad_url_name: ''
- ad_url_id: '11280'
  ad_url_name: ''
- ad_url_id: '11281'
  ad_url_name: ''
- ad_url_id: '11282'
  ad_url_name: ''
- ad_url_id: '11284'
  ad_url_name: ''
- ad_url_id: '11288'
  ad_url_name: ''
- ad_url_id: '11290'
  ad_url_name: ''
- ad_url_id: '11292'
  ad_url_name: ''
- ad_url_id: '11293'
  ad_url_name: ''
- ad_url_id: '11294'
  ad_url_name: ''
- ad_url_id: '11295'
  ad_url_name: ''
- ad_url_id: '11296'
  ad_url_name: ''
- ad_url_id: '11314'
  ad_url_name: ''
- ad_url_id: '11355'
  ad_url_name: ''
- ad_url_id: '11357'
  ad_url_name: ''
- ad_url_id: '11359'
  ad_url_name: ''
- ad_url_id: '11364'
  ad_url_name: ''
- ad_url_id: '11386'
  ad_url_name: ''
- ad_url_id: '11387'
  ad_url_name: ''
- ad_url_id: '11565'
  ad_url_name: ''
- ad_url_id: '11575'
  ad_url_name: ''
- ad_url_id: '11576'
  ad_url_name: ''
- ad_url_id: '11583'
  ad_url_name: ''
- ad_url_id: '11586'
  ad_url_name: ''
- ad_url_id: '11591'
  ad_url_name: ''
- ad_url_id: '11595'
  ad_url_name: ''
- ad_url_id: '11596'
  ad_url_name: ''
- ad_url_id: '11607'
  ad_url_name: ''
- ad_url_id: '11609'
  ad_url_name: ''
- ad_url_id: '11715'
  ad_url_name: ''
- ad_url_id: '11717'
  ad_url_name: ''
- ad_url_id: '11719'
  ad_url_name: ''
- ad_url_id: '11724'
  ad_url_name: ''
- ad_url_id: '11725'
  ad_url_name: ''
- ad_url_id: '11726'
  ad_url_name: ''
- ad_url_id: '11728'
  ad_url_name: ''
- ad_url_id: '11734'
  ad_url_name: ''
- ad_url_id: '11752'
  ad_url_name: ''
- ad_url_id: '11758'
  ad_url_name: ''
- ad_url_id: '11759'
  ad_url_name: ''
- ad_url_id: '11760'
  ad_url_name: ''
- ad_url_id: '11761'
  ad_url_name: ''
- ad_url_id: '11762'
  ad_url_name: ''
- ad_url_id: '11763'
  ad_url_name: ''
- ad_url_id: '11764'
  ad_url_name: ''
- ad_url_id: '11769'
  ad_url_name: ''
- ad_url_id: '11770'
  ad_url_name: ''
- ad_url_id: '11771'
  ad_url_name: ''
- ad_url_id: '11772'
  ad_url_name: ''
- ad_url_id: '11773'
  ad_url_name: ''
- ad_url_id: '11776'
  ad_url_name: ''
- ad_url_id: '11777'
  ad_url_name: ''
- ad_url_id: '11925'
  ad_url_name: ''
- ad_url_id: '11937'
  ad_url_name: ''
- ad_url_id: '11938'
  ad_url_name: ''
- ad_url_id: '11940'
  ad_url_name: ''
- ad_url_id: '11943'
  ad_url_name: ''
- ad_url_id: '11948'
  ad_url_name: ''
- ad_url_id: '11952'
  ad_url_name: ''
- ad_url_id: '11953'
  ad_url_name: ''
- ad_url_id: '11955'
  ad_url_name: ''
- ad_url_id: '12074'
  ad_url_name: ''
- ad_url_id: '12075'
  ad_url_name: ''
- ad_url_id: '12080'
  ad_url_name: ''
- ad_url_id: '12082'
  ad_url_name: ''
- ad_url_id: '12106'
  ad_url_name: ''
- ad_url_id: '12107'
  ad_url_name: ''
- ad_url_id: '12110'
  ad_url_name: ''
- ad_url_id: '12112'
  ad_url_name: ''
- ad_url_id: '12113'
  ad_url_name: ''
- ad_url_id: '12114'
  ad_url_name: ''
- ad_url_id: '12137'
  ad_url_name: ''
- ad_url_id: '12157'
  ad_url_name: ''
- ad_url_id: '12160'
  ad_url_name: ''
- ad_url_id: '12161'
  ad_url_name: ''
- ad_url_id: '12253'
  ad_url_name: ''
- ad_url_id: '12254'
  ad_url_name: swt_kl_v1_SMNW
- ad_url_id: '12378'
  ad_url_name: ''
- ad_url_id: '12379'
  ad_url_name: ''
- ad_url_id: '12380'
  ad_url_name: ''
- ad_url_id: '12471'
  ad_url_name: ''
- ad_url_id: '3607'
  ad_url_name: ''
- ad_url_id: '3607.0'
  ad_url_name: ''
- ad_url_id: '3761'
  ad_url_name: ''
- ad_url_id: '3761.0'
  ad_url_name: ''
- ad_url_id: '3762'
  ad_url_name: ''
- ad_url_id: '3762.0'
  ad_url_name: ''
- ad_url_id: '3763'
  ad_url_name: ''
- ad_url_id: '3763.0'
  ad_url_name: ''
- ad_url_id: '3764'
  ad_url_name: ''
- ad_url_id: '3764.0'
  ad_url_name: ''
- ad_url_id: '3791'
  ad_url_name: ''
- ad_url_id: '3791.0'
  ad_url_name: ''
- ad_url_id: '3792'
  ad_url_name: ''
- ad_url_id: '3792.0'
  ad_url_name: ''
- ad_url_id: '3815'
  ad_url_name: ''
- ad_url_id: '3815.0'
  ad_url_name: ''
- ad_url_id: '3816'
  ad_url_name: ''
- ad_url_id: '3816.0'
  ad_url_name: ''
- ad_url_id: '3817'
  ad_url_name: ''
- ad_url_id: '3817.0'
  ad_url_name: ''
- ad_url_id: '3818'
  ad_url_name: ''
- ad_url_id: '4188'
  ad_url_name: ''
- ad_url_id: '4188.0'
  ad_url_name: ''
- ad_url_id: '4189.0'
  ad_url_name: ''
- ad_url_id: '4205'
  ad_url_name: ''
- ad_url_id: '4205.0'
  ad_url_name: ''
- ad_url_id: '4279'
  ad_url_name: ''
- ad_url_id: '4279.0'
  ad_url_name: ''
- ad_url_id: '4475.0'
  ad_url_name: ''
- ad_url_id: '4722'
  ad_url_name: ''
- ad_url_id: '4722.0'
  ad_url_name: ''
- ad_url_id: '4723'
  ad_url_name: ''
- ad_url_id: '4723.0'
  ad_url_name: ''
- ad_url_id: '4878'
  ad_url_name: ''
- ad_url_id: '4878.0'
  ad_url_name: ''
- ad_url_id: '4879'
  ad_url_name: ''
- ad_url_id: '4879.0'
  ad_url_name: ''
- ad_url_id: '4914'
  ad_url_name: ''
- ad_url_id: '4914.0'
  ad_url_name: ''
- ad_url_id: '4915'
  ad_url_name: ''
- ad_url_id: '4915.0'
  ad_url_name: ''
- ad_url_id: '5084'
  ad_url_name: ''
- ad_url_id: '5084.0'
  ad_url_name: ''
- ad_url_id: '5085'
  ad_url_name: ''
- ad_url_id: '5085.0'
  ad_url_name: ''
- ad_url_id: '6209'
  ad_url_name: ''
- ad_url_id: '6209.0'
  ad_url_name: ''
- ad_url_id: '6212'
  ad_url_name: ''
- ad_url_id: '6212.0'
  ad_url_name: ''
- ad_url_id: '6546'
  ad_url_name: ''
- ad_url_id: '6546.0'
  ad_url_name: ''
- ad_url_id: '6549'
  ad_url_name: ''
- ad_url_id: '6549.0'
  ad_url_name: ''
- ad_url_id: '6552'
  ad_url_name: ''
- ad_url_id: '6552.0'
  ad_url_name: ''
- ad_url_id: '6555.0'
  ad_url_name: ''
- ad_url_id: '6556'
  ad_url_name: ''
- ad_url_id: '6556.0'
  ad_url_name: ''
- ad_url_id: '6558'
  ad_url_name: ''
- ad_url_id: '6558.0'
  ad_url_name: ''
- ad_url_id: '6563'
  ad_url_name: ''
- ad_url_id: '6563.0'
  ad_url_name: ''
- ad_url_id: '6564'
  ad_url_name: ''
- ad_url_id: '6564.0'
  ad_url_name: ''
- ad_url_id: '6565'
  ad_url_name: ''
- ad_url_id: '6565.0'
  ad_url_name: ''
- ad_url_id: '6629'
  ad_url_name: ''
- ad_url_id: '6629.0'
  ad_url_name: ''
- ad_url_id: '6630'
  ad_url_name: ''
- ad_url_id: '6632'
  ad_url_name: ''
- ad_url_id: '6632.0'
  ad_url_name: ''
- ad_url_id: '6687'
  ad_url_name: ''
- ad_url_id: '6687.0'
  ad_url_name: ''
- ad_url_id: '6688'
  ad_url_name: ''
- ad_url_id: '6688.0'
  ad_url_name: ''
- ad_url_id: '6692'
  ad_url_name: ''
- ad_url_id: '6692.0'
  ad_url_name: ''
- ad_url_id: '7176'
  ad_url_name: ''
- ad_url_id: '7228'
  ad_url_name: ''
- ad_url_id: '7339'
  ad_url_name: ''
- ad_url_id: '7360'
  ad_url_name: ''
- ad_url_id: '7362'
  ad_url_name: ''
- ad_url_id: '7665'
  ad_url_name: ''
- ad_url_id: '7672'
  ad_url_name: ''
- ad_url_id: '7873'
  ad_url_name: ''
- ad_url_id: '7894'
  ad_url_name: ''
- ad_url_id: '8151'
  ad_url_name: ''
- ad_url_id: '8160'
  ad_url_name: ''
- ad_url_id: '8161'
  ad_url_name: ''
- ad_url_id: '8181'
  ad_url_name: ''
- ad_url_id: '8182'
  ad_url_name: ''
- ad_url_id: '8183'
  ad_url_name: ''
- ad_url_id: '8188'
  ad_url_name: ''
- ad_url_id: '8189'
  ad_url_name: ''
- ad_url_id: '8194'
  ad_url_name: ''
- ad_url_id: '8263'
  ad_url_name: ''
- ad_url_id: '8264'
  ad_url_name: ''
- ad_url_id: '8265'
  ad_url_name: ''
- ad_url_id: '8303'
  ad_url_name: ''
- ad_url_id: '8574'
  ad_url_name: ''
- ad_url_id: '8576'
  ad_url_name: ''
- ad_url_id: '8580'
  ad_url_name: ''
- ad_url_id: '8609'
  ad_url_name: ''
- ad_url_id: '8610'
  ad_url_name: ''
- ad_url_id: '8611'
  ad_url_name: ''
- ad_url_id: '8693'
  ad_url_name: ''
- ad_url_id: '8862'
  ad_url_name: ''
- ad_url_id: '8863'
  ad_url_name: ''
- ad_url_id: '8939'
  ad_url_name: ''
- ad_url_id: '8940'
  ad_url_name: ''
- ad_url_id: '9287'
  ad_url_name: ''
- ad_url_id: '9288'
  ad_url_name: ''
- ad_url_id: '9291'
  ad_url_name: ''
- ad_url_id: '9646'
  ad_url_name: ''
- ad_url_id: '9689'
  ad_url_name: ''
