mappings:
- label: シュサノンα(プレゼント無し)
  numerator_names:
  - シュサノンα【180日間全額返金保証・定期コース】
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  denominator_names:
  - シュサノン内服錠【180日間全額返金保証・定期コース】
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_TK
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_1d
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_4d
  - シュサノンα【180日間全額返金保証・定期コース】
  period_ref_names:
  - シュサノンα【180日間全額返金保証・定期コース】
- label: シュサノンα(スキンケアプレゼント)
  numerator_names:
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
  denominator_names:
  - シュサノン内服錠【180日間全額返金保証・定期コース】
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_4d
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_TK
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_1d
  period_ref_names:
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
- label: シュサノンあぷあぷ
  numerator_names:
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  denominator_names:
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
  period_ref_names:
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
