mappings:
- from_names:
  - シュサノン内服錠【180日間全額返金保証・定期コース】
  upsell_name: シュサノンα【180日間全額返金保証・定期コース】
  upsell_upsell_name: null
- from_names:
  - シュサノン内服錠【180日間全額返金保証・定期コース】
  upsell_name: シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
  upsell_upsell_name: null
