mappings:
- from_names: &id001
  - シュサノン内服錠【180日間全額返金保証・定期コース】
  - シュサノンα【260日間全額返金保証・実質1袋永久無料・初回スキンケアセット付定期コース】_CHG
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_TK
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_1d
  - シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG_MUSL_ST_4d
  upsell_name: シュサノンα【180日間全額返金保証・定期コース】
  upsell_upsell_name: null
- from_names: *id001
  upsell_name: シュサノンα【180日間全額返金保証・初回スキンケアセット付定期コース】_CHG
  upsell_upsell_name: null
